// Generates src/case_tables.cc — Unicode SIMPLE case mappings.
//
//   c++ -std=c++23 tools/gen_case_tables.cc $(pkg-config --cflags --libs icu-uc) \
//       -o /tmp/gen_case && /tmp/gen_case > src/case_tables.cc
//
// ICU is needed to REGENERATE the table and is not linked into anything the
// project ships: the checked-in output is a pair of plain arrays. Linking ICU
// itself would put ~30MB of locale data into every compiled pipeline, which is
// a poor trade for a table that changes once per Unicode release.
//
// Simple, not full, case mapping. That is what the reference does -- it maps
// rune by rune, so "straße".uppercase() is "STRAßE" and not "STRASSE", and
// "ﬁn".uppercase() is "ﬁN". Deriving the table from Python's str.upper()
// instead was tried and is wrong for 27 code points: the Greek
// iota-subscript characters (U+1F80 and friends) have a two-character FULL
// uppercase, so a "use it only when it is one character" rule maps them to
// themselves, while their simple uppercase is a real and different character.
#include <unicode/uchar.h>

#include <cstdint>
#include <cstdio>
#include <vector>

int main() {
    struct entry { uint32_t from; int32_t delta; };
    std::vector<entry> up, down;
    for (UChar32 c = 0; c <= 0x10FFFF; ++c) {
        const UChar32 u = u_toupper(c);
        const UChar32 l = u_tolower(c);
        if (u != c) up.push_back({static_cast<uint32_t>(c), static_cast<int32_t>(u - c)});
        if (l != c) down.push_back({static_cast<uint32_t>(c), static_cast<int32_t>(l - c)});
    }

    std::printf(
        "// Generated by tools/gen_case_tables.cc -- do not edit.\n"
        "//\n"
        "// Unicode simple case mappings, as (code point, delta) pairs sorted by code\n"
        "// point. Stored as deltas because most of them are shared by long runs, which\n"
        "// keeps the arrays compressible and the diffs readable when Unicode changes.\n"
        "#include \"case_tables.hh\"\n\n"
        "namespace sf::ucase {\n\n");

    auto emit = [](const char* name, const std::vector<entry>& v) {
        std::printf("const case_entry %s[] = {\n", name);
        for (size_t i = 0; i < v.size(); ++i) {
            if (i % 4 == 0) std::printf("    ");
            std::printf("{0x%05X, %6d},", v[i].from, v[i].delta);
            std::printf((i % 4 == 3) ? "\n" : " ");
        }
        if (v.size() % 4) std::printf("\n");
        std::printf("};\nconst size_t %s_len = %zu;\n\n", name, v.size());
    };
    emit("UPPER", up);
    emit("LOWER", down);
    std::printf("} // namespace sf::ucase\n");
    return 0;
}
