#!/usr/bin/env python3
"""Generate src/blowfish_tables.cc.

Blowfish's initial P-array and S-boxes are not arbitrary: they are the first
8336 hexadecimal digits of the fractional part of pi, which is how the design
demonstrates that it hides no trapdoor. Computing them here rather than pasting
a table from somewhere means the provenance is checkable: the assertion below
pins the first 32 digits against the published value, and the compare_bcrypt
fixtures pin the resulting cipher against hashes produced elsewhere.

Machin's formula in exact integer arithmetic; no floating point anywhere, so
the digits are exact rather than nearly right.
"""
import pathlib

NWORDS = 18 + 4 * 256          # the P-array plus four S-boxes
NDIG = NWORDS * 8
GUARD = 32                     # extra digits, so the last one is not rounded


def atan_inv(x: int, scale: int) -> int:
    """scale * atan(1/x), truncated."""
    total = 0
    term = scale // x
    k = 0
    xx = x * x
    while term:
        d = term // (2 * k + 1)
        total += d if k % 2 == 0 else -d
        term //= xx
        k += 1
    return total


def main() -> None:
    scale = 16 ** (NDIG + GUARD)
    pi = 16 * atan_inv(5, scale) - 4 * atan_inv(239, scale)
    digits = format(pi - 3 * scale, "x").rjust(NDIG + GUARD, "0")
    assert digits.startswith("243f6a8885a308d313198a2e03707344"), digits[:40]
    words = [int(digits[i * 8:(i + 1) * 8], 16) for i in range(NWORDS)]

    out = ['// Generated by tools/gen_blowfish_tables.py -- do not edit.',
           '//',
           "// Blowfish's initial state: the first 8336 hexadecimal digits of pi's",
           '// fractional part. See the generator for why this is computed rather than',
           '// copied, and tests/test_all.cc for the check that pins it against OpenSSL.',
           '#include "blowfish_tables.hh"',
           '',
           'namespace sf::bf {',
           '',
           'const uint32_t INIT_P[18] = {']
    for i in range(0, 18, 6):
        out.append('    ' + ' '.join(f"0x{w:08x}," for w in words[i:i + 6]))
    out.append('};')
    out.append('')
    out.append('const uint32_t INIT_S[4][256] = {')
    for box in range(4):
        out.append('    {')
        chunk = words[18 + box * 256: 18 + (box + 1) * 256]
        for i in range(0, 256, 6):
            out.append('        ' + ' '.join(f"0x{w:08x}," for w in chunk[i:i + 6]))
        out.append('    },')
    out.append('};')
    out.append('')
    out.append('} // namespace sf::bf')
    dest = pathlib.Path(__file__).resolve().parents[1] / "src/blowfish_tables.cc"
    dest.write_text("\n".join(out) + "\n")
    print(f"{NWORDS} words -> {dest}")


if __name__ == "__main__":
    main()
