// The Blowfish initial state, generated by tools/gen_blowfish_tables.py.
#pragma once
#include <cstdint>

namespace sf::bf {
extern const uint32_t INIT_P[18];
extern const uint32_t INIT_S[4][256];
}
