// Unicode simple case mappings, generated by tools/gen_case_tables.cc.
#pragma once
#include <cstddef>
#include <cstdint>

namespace sf::ucase {
struct case_entry { uint32_t from; int32_t delta; };
extern const case_entry UPPER[];
extern const size_t     UPPER_len;
extern const case_entry LOWER[];
extern const size_t     LOWER_len;
}
